import type { Metadata } from 'next'
import { font } from './fonts'
import './globals.css'
import React from "react";
import Footer from '@/src/shared/ui/footer/footer';
import Header from '@/src/shared/ui/header/header';


export const metadata: Metadata = {
  title: 'Изумрудный город - центр адаптации и развития',
  description: 'Generated by create next app', // TODO: Добавить описание сайта по умолчанию
}

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <html lang="ru">
      <body className={font.className}>
        <Header isIndexPage={false} />
        <main className="mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout;
